import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outDir = "dist";

/** After the build, copy manifest.json and styles.css to dist when they exist in the project root so the full package is installable. */
const copyPlugin = {
	name: 'copy-plugin-files',
	setup(build) {
		build.onEnd(() => {
			const cwd = process.cwd();
			if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
			const manifestSrc = join(cwd, 'manifest.json');
			const stylesSrc = join(cwd, 'styles.css');
			const viewerSrc = join(cwd, 'assets', 'viewer-static.min.cjs');
			if (existsSync(manifestSrc)) copyFileSync(manifestSrc, join(cwd, outDir, 'manifest.json'));
			if (existsSync(stylesSrc)) copyFileSync(stylesSrc, join(cwd, outDir, 'styles.css'));
			if (existsSync(viewerSrc)) copyFileSync(viewerSrc, join(cwd, outDir, 'viewer-static.min.cjs'));
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(outDir, "main.js"),
	minify: prod,
	loader: { ".wasm": "binary" },
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
